### PR TITLE
Some panning invert + L/Rcross in StereoHarm

### PR DESCRIPTION
**Pull request by rcspam**
Hi,
Just solve some "invert panning" in some plugins + correct "L/R Crossover" in StereoHarm with @brummer10's fix.
I hope it's help ;) and it's right...

### CODE REVIEW

**Comment by ssj71** [comment]
can you verify if these are also inverted in rakarrack? I'd like to make sure we aren't breaking the standalone app.

**Comment by ssj71** [comment]
oh and thanks for the pull request! These are very helpful!

**Comment by rcspam** [comment]
The pan error is inrakarrack !!
But why not fix it, if rakarrack devel is stoped ?

**Comment by ssj71** [comment]
I will fix it. I just don't want to BREAK rakarrack trying to fix the plugins.

**Comment by rcspam** [comment]
It's your choice, i understand...

**Comment by rcspam** [comment]
... but why accept the pull request ?

**Comment by ssj71** [comment]
because you said the problem is also in rakarrack. It is now FIXED in rakarrack and in rkr lv2.

**Comment by rcspam** [comment]
Cool  ;)

**Pull request merged**
